# Generated by Django 5.2 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown after quiz submission'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
