# Generated by Django 5.2 on 2026-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_question_explanation_takenquiz_time_taken'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('name', 'subject'), name='unique_name_subject'),
        ),
    ]
